fillpdf.settings:
  type: config_object
  label: 'FillPDF Settings'
  mapping:
    backend:
      type: string
      label: 'PDF processing method'
    remote_protocol:
      type: string
      label: 'FillPDF Service endpoint protocol'
    remote_endpoint:
      type: string
      label: 'FillPDF Service endpoint URL without protocol'
    fillpdf_service:
      type: string
      label: 'Which PDF filling backend to use'
    fillpdf_service_api_key:
      type: string
      label: 'FillPDF Service API key'
    allowed_schemes:
      type: sequence
      label: 'Allowed storage schemes'
      sequence:
        type: string
        label: 'Allowed storage scheme'
    template_scheme:
      type: string
      label: 'Template storage scheme'
    local_service_endpoint:
      type: string
      label: 'Local FillPDF PDF API endpoint'
    pdftk_path:
      type: string
      label: 'Path to the pdftk command'
    shell_locale:
      type: string
      label: 'Locale for escaping shell commands'
